global:
  # Deploys aws specific ingress
  aws: 
    enabled: true
  environment: dev
  # Deploys elasticsearch and postgres in k8s
  dev: true
  # Replace with your dev environment url. 
  hostname: devgen3.test.biocommons.org.au
  # this is arn to a certificate in AWS that needs to match the hostname.
  revproxyArn: arn:aws:acm:ap-southeast-2:232870232581:certificate/263d28c1-6e7d-4365-adc2-aa459d7ac847


# configuration for fence helm chart. You can add it for all our services.
fence:
  # Override image
  image:
    repository: quay.io/cdis/fence
    tag: automatedCopy-feature_oidc-oauth-groups

  # Fence config overrides 
  FENCE_CONFIG:
    APP_NAME: 'Gen3 Data Commons'
    # A URL-safe base64-encoded 32-byte key for encrypting keys in db
    # in python you can use the following script to generate one:
    #     import base64
    #     import os
    #     key = base64.urlsafe_b64encode(os.urandom(32))
    #     print(key)
    ENCRYPTION_KEY: REPLACEME

    DEBUG: True
    OPENID_CONNECT:
      google:
        client_id: ""
        client_secret: ""

    AWS_CREDENTIALS:
      'fence-bot':
        aws_access_key_id: ''
        aws_secret_access_key: ''

    S3_BUCKETS:
      # Name of the actual s3 bucket
      jq-helm-testing:
        cred: 'fence-bot'
        region: us-east-1
    
    # This is important for data upload.
    DATA_UPLOAD_BUCKET: 'jq-helm-testing'

portal:
  image:
    repository: quay.io/cdis/data-portal
    tag: "master"
    pullPolicy: Always
  enabled: true
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json
  resources:
    requests:
      cpu: 2.0
      memory: 8192Mi
    limits:
      cpu: 2.0
      memory: 8192Mi

pelican:
  enabled: false

# -- (map) To configure postgresql subchart
# Persistence is disabled by default
postgresql:
  primary:
    persistence:
      # -- (bool) Option to persist the dbs data.
      enabled: true

sower:
  enabled: false