argocdapp:
  destinationServer: ''
  argoProjectNamespace: ''
  argoNamespace: ''

  labels:
    env: dev
  spec:
    destination:
      server: https://kubernetes.default.svc
    project: dev
    namespace: dev
    sources:
      - repoURL: 'https://github.com/uc-cdis/gen3-helm.git'
        path: helm/gen3
        targetRevision: master
        helm:
          valueFiles:
            - $values/environments/dev/gen3-values.yaml
      - repoURL: 'https://github.com/AustralianBioCommons/gen3-workloads-example.git'
        targetRevision: fence-testing
        ref: values